### ISSUE TITLE
No way to set onStopTrackingTouch listener?

### ISSUE THREAD

**Issue by IncioMan** [JesusM/HoloCircleSeekBar#11]
Hi. great job with the this seekbar. Just two problems:

The first one is that is not possible to implement all the methods of OnSeekBar listener, and I really need onStopTrackingTouch. Is there a way?

The second is that when I set initPosition the text show the right value but the seekbar is way to small then if I drag it to that value.

Thanks in advance

**Comment by JesusM** [comment]
@IncioMan Thanks for the suggestion, the other two methods from SeekBar.OnSeekBarChangeListeners have been added in https://github.com/JesusM/HoloCircleSeekBar/commit/7e8bb9ba03a35770d315c2b4d4ac7fd7162dd32a

**Comment by IncioMan** [comment]
Thank you, I really appriciate. How to update the version I included in my project through jitpack? The version does not update.

**Comment by JesusM** [comment]
@IncioMan I've added a Release tag note so you can check this new version here https://jitpack.io/#JesusM/HoloCircleSeekBar/v2.2.1

**Comment by IncioMan** [comment]
I managed!! Thank you really much! You're awesome!

May I ask you one more thing? I making this app as university project. If one day I wanted to publish it on the Play Store, should I remove the HoloCircleSeekBar ? Or should I just mention that the HoloCircleSeekBar component is yours? I don't know how this things with rights and stuff works. 

Thanks for your time and work.

**Comment by JesusM** [comment]
@IncioMan It would be awesome if the library is so useful for you that you finally use it for a published app. It's published under Apache License 2, so you can use it for commercial purpose. It would be awesome if you mention and link the library project from your app.
