### ISSUE TITLE
setValue Problem

### ISSUE THREAD

**Issue by pepade84** [JesusM/HoloCircleSeekBar#13]
If I set the setMax to 100 and I am trying to set the value to this MaxValue, it doesnt work. 

I think there should be a change in your "setValue" Method that the newValue <= instead of only "<". 

 public void setValue(float newValue) {
        if (newValue < max) {
....
}

Another strange behaviour is, while I am trying to set the value to "0", the text will be set to "1"...

**Comment by ptrdtznr** [comment]
solved in V2.2.3
