### ISSUE TITLE
can't run in the backend

### ISSUE THREAD

**Issue by MarkShawn2020** [JesusM/HoloCircleSeekBar#24]
Have you considered about the circumstance when app is running in the backend?

I happened to find that it would stop calculating seconds when the system changed to be locked.

**Comment by JesusM** [comment]
Hi @MarkShawn2020 , thanks for being interested in the library.
Not 100% sure what you mean, but the library pretty much works from "direct" interactions (either via setting the value, or manually interacting with the widget). Happy to help if you can provide details about the use case for the widget.

**Comment by MarkShawn2020** [comment]
Hi, thanks for you reply. I mean if the app goes to the backend, then the component of this app would be slept / locked, so that doesn't work.

Didn't you notice this? Or maybe I should force app not to constraint by the power charge?

**Comment by MarkShawn2020** [comment]
closed since not foucused now.
