### ISSUE TITLE
Seekbar not changing

### ISSUE THREAD

**Issue by 29jitender** [JesusM/HoloCircleSeekBar#3]
Seekbar only working when dragging it from starting. When i stop it in between and try to move pointer again it doesn't work I have to move pointer from the top again and tapping on wheel is also not changing pointer position.

Using this in xml
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    app:max="60"
                    app:pointer_color="#6AFF0D"
                    app:pointer_halo_color="#336AFF0D"
                    app:pointer_size="24"
                    app:text_color="#E8A10C"
                    app:text_size="65"
                    app:wheel_size="8"
                    app:color="#cfcfcf"
                    app:wheel_active_color="#00BFFF"
                    app:wheel_unactive_color="#5500BFFF"

**Comment by JesusM** [comment]
@29jitender Hi, I've tried the reproduce the problem you are having but for me that behaviour is working correctly. In this link (https://drive.google.com/open?id=0B3_15qFiB8KVRmYwRXNuTko0NlU) you can check a video in which the app is working fine moving the pointer. Please let me know if I misunderstand something of your description of the problem.

**Comment by JesusM** [comment]
I'm going to close it for now as no new information has been added.
