### ISSUE TITLE
Un-needed attribute

### ISSUE THREAD

**Issue by bizzguy** [JesusM/HoloCircleSeekBar#4]
It appears that the color attribute defined in "attrs.xml" is not needed and it conflicts with newer versions of the API

        <attr name="color" format="string"></attr>

**Comment by JesusM** [comment]
Thanks for the comment. I would like to keep updated the repo, I will try to take a look and work on it.

**Comment by bizzguy** [comment]
I had a chance to look at it in a bit more detail.  It appears that "color"
was an attribute from the original color wheel version and isn't needed
anymore.  It also conflicts with an attribute in API 21 (maybe earlier than
that - although I didn't verify that).  I've made the changes in my own
fork.  Would you like me to do a pull request?

**Comment by JesusM** [comment]
Sure!Do it and I will check it!Thanks!

**Comment by bizzguy** [comment]
Hi,

I submitted the pull request (at least I think I did - it is my first one).


Jim

**Comment by JesusM** [comment]
I just merged it. Thanks!
