### ISSUE TITLE
Maximum value of SeekBar

### ISSUE THREAD

**Issue by AToleuov** [JesusM/HoloCircleSeekBar#9]
Hello,
Thanks for your great widget. It looks awesome. 
I am just having a problem with setting the max value of the SeekBar programmatically? Is it even possible? Because I really need to make the widget more flexible in my app. Can you suggest something?
I would really appreciate your help.
P.S.: Hello from a Kazakhstan Android developer!

**Comment by JesusM** [comment]
Closed because it has been added in https://github.com/JesusM/HoloCircleSeekBar/commit/7eb2dec5105f3c0122a2534c10a1b4a03ba23dfd
